services:
  app:
    build:
      context: ./laravel_react_crud
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./react_laravel_crud
      dockerfile: Dockerfile
    image: react-app
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
